In [245]:
# Decison tree datalarni qismlarga featuralarga ko'ra ajratadi(Tree structurasiga o'xshab)
# Root node (Birinchi decisionnuqta)
# Decision node ( Turli cil featurelarga ko'ra yana qismlarga ajratiladigan node)
# Leaf nodes (Tree yordamida olingan Yakuni qaror yoki predict)

In [246]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score

In [247]:
df = pd.read_csv(r'C:\Users\Maftuna\Downloads\Telegram Desktop\student_data.csv')

In [248]:
df

Student ID     Student Name Date of Birth          Field of Study  \
0           165527     Bryan Rogers    2006-01-19        Computer Science   
1           635763      James Hogan    1999-05-23  Mechanical Engineering   
2           740021   David Robinson    1997-12-02       Civil Engineering   
3           433076     Susan Miller    1999-10-30        Computer Science   
4           441628  Brittany Martin    1998-01-10    Chemical Engineering   
...            ...              ...           ...                     ...   
199995      220556    Kelly Bradley    2001-06-06  Electrical Engineering   
199996      957592      Jacob Smith    2003-12-15  Electrical Engineering   
199997      786798     Nicole Davis    2000-07-27    Chemical Engineering   
199998      142498  Natasha Rosales    2001-02-16       Civil Engineering   
199999      930898    Charles Marsh    2005-10-17        Computer Science   

        Year of Admission  Expected Year of Graduation  Current Semester  \
0                    2020                         2017                 3   
1                    2020                         2020                 2   
2                    2017                         2022                 1   
3                    2021                         2019                 1   
4                    2016                         2018                 1   
...                   ...                          ...               ...   
199995               2017                         2021                 4   
199996               2017                         2019                 3   
199997               2022                         2023                 1   
199998               2017                         2018                 1   
199999               2018                         2020                 2   

          Specialization    Fees  Discount on Fees  
0        Web Development  155152             19572  
1       Machine Learning  157870             14760  
2       Network Security   55662              5871  
3           Data Science  134955             17284  
4       Network Security  125934             14871  
...                  ...     ...               ...  
199995      Data Science  164149              4246  
199996   Web Development  135184             12729  
199997      Data Science  139430             18237  
199998      Data Science   73117              6946  
199999  Machine Learning   75582              6176  

[200000 rows x 10 columns]

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   Student ID                   200000 non-null  int64 
 1   Student Name                 200000 non-null  object
 2   Date of Birth                200000 non-null  object
 3   Field of Study               200000 non-null  object
 4   Year of Admission            200000 non-null  int64 
 5   Expected Year of Graduation  200000 non-null  int64 
 6   Current Semester             200000 non-null  int64 
 7   Specialization               200000 non-null  object
 8   Fees                         200000 non-null  int64 
 9   Discount on Fees             200000 non-null  int64 
dtypes: int64(6), object(4)
memory usage: 15.3+ MB


In [250]:
df.isnull().sum()

Student ID                     0
Student Name                   0
Date of Birth                  0
Field of Study                 0
Year of Admission              0
Expected Year of Graduation    0
Current Semester               0
Specialization                 0
Fees                           0
Discount on Fees               0
dtype: int64

In [251]:
df.drop(columns=['Student ID', 'Student Name'], inplace=True)

In [252]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   Date of Birth                200000 non-null  object
 1   Field of Study               200000 non-null  object
 2   Year of Admission            200000 non-null  int64 
 3   Expected Year of Graduation  200000 non-null  int64 
 4   Current Semester             200000 non-null  int64 
 5   Specialization               200000 non-null  object
 6   Fees                         200000 non-null  int64 
 7   Discount on Fees             200000 non-null  int64 
dtypes: int64(5), object(3)
memory usage: 12.2+ MB


In [253]:
df['Date of Birth']

0         2006-01-19
1         1999-05-23
2         1997-12-02
3         1999-10-30
4         1998-01-10
             ...    
199995    2001-06-06
199996    2003-12-15
199997    2000-07-27
199998    2001-02-16
199999    2005-10-17
Name: Date of Birth, Length: 200000, dtype: object

In [254]:
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'], errors='coerce')

In [255]:
df['Year'] = df['Date of Birth'].dt.year
df['Day'] = df['Date of Birth'].dt.day
df['Weekday'] = df['Date of Birth'].dt.weekday  # Monday=0, Sunday=6
df['Month'] = df['Date of Birth'].dt.month

In [256]:
df['Age'] = 2024 - df['Date of Birth'].dt.year

In [257]:
df.drop(columns=['Date of Birth'], inplace=True)

In [258]:
df['Net Fees'] = df['Fees'] - df['Discount on Fees']


In [259]:
df.head()

Field of Study  Year of Admission  Expected Year of Graduation  \
0        Computer Science               2020                         2017   
1  Mechanical Engineering               2020                         2020   
2       Civil Engineering               2017                         2022   
3        Computer Science               2021                         2019   
4    Chemical Engineering               2016                         2018   

   Current Semester    Specialization    Fees  Discount on Fees  Year  Day  \
0                 3   Web Development  155152             19572  2006   19   
1                 2  Machine Learning  157870             14760  1999   23   
2                 1  Network Security   55662              5871  1997    2   
3                 1      Data Science  134955             17284  1999   30   
4                 1  Network Security  125934             14871  1998   10   

   Weekday  Month  Age  Net Fees  
0        3      1   18    135580  
1        6      5   25    143110  
2        1     12   27     49791  
3        5     10   25    117671  
4        5      1   26    111063

In [260]:
df['Expected Year of Graduation'] = df['Year of Admission'] + 4

In [261]:
df.head()  

Field of Study  Year of Admission  Expected Year of Graduation  \
0        Computer Science               2020                         2024   
1  Mechanical Engineering               2020                         2024   
2       Civil Engineering               2017                         2021   
3        Computer Science               2021                         2025   
4    Chemical Engineering               2016                         2020   

   Current Semester    Specialization    Fees  Discount on Fees  Year  Day  \
0                 3   Web Development  155152             19572  2006   19   
1                 2  Machine Learning  157870             14760  1999   23   
2                 1  Network Security   55662              5871  1997    2   
3                 1      Data Science  134955             17284  1999   30   
4                 1  Network Security  125934             14871  1998   10   

   Weekday  Month  Age  Net Fees  
0        3      1   18    135580  
1        6      5   25    143110  
2        1     12   27     49791  
3        5     10   25    117671  
4        5      1   26    111063

In [262]:
df['Study Duration'] = df['Expected Year of Graduation'] - df['Year of Admission']


In [263]:
df['Fee per Semester'] = df['Net Fees'] / (df['Study Duration'] * 2)


In [264]:
df['Admission Age'] = df['Year of Admission'] - (2024 - df['Age'])


In [265]:
df.head()

Field of Study  Year of Admission  Expected Year of Graduation  \
0        Computer Science               2020                         2024   
1  Mechanical Engineering               2020                         2024   
2       Civil Engineering               2017                         2021   
3        Computer Science               2021                         2025   
4    Chemical Engineering               2016                         2020   

   Current Semester    Specialization    Fees  Discount on Fees  Year  Day  \
0                 3   Web Development  155152             19572  2006   19   
1                 2  Machine Learning  157870             14760  1999   23   
2                 1  Network Security   55662              5871  1997    2   
3                 1      Data Science  134955             17284  1999   30   
4                 1  Network Security  125934             14871  1998   10   

   Weekday  Month  Age  Net Fees  Study Duration  Fee per Semester  \
0        3      1   18    135580               4         16947.500   
1        6      5   25    143110               4         17888.750   
2        1     12   27     49791               4          6223.875   
3        5     10   25    117671               4         14708.875   
4        5      1   26    111063               4         13882.875   

   Admission Age  
0             14  
1             21  
2             20  
3             22  
4             18

In [266]:
# Count the number of rows where 'Admission Age' is less than 16
under_16_count = (df['Admission Age'] < 16).sum()


print(f"Number of rows with Admission Age under 16: {under_16_count}")

Number of rows with Admission Age under 16: 55479


In [267]:
df.head()

Field of Study  Year of Admission  Expected Year of Graduation  \
0        Computer Science               2020                         2024   
1  Mechanical Engineering               2020                         2024   
2       Civil Engineering               2017                         2021   
3        Computer Science               2021                         2025   
4    Chemical Engineering               2016                         2020   

   Current Semester    Specialization    Fees  Discount on Fees  Year  Day  \
0                 3   Web Development  155152             19572  2006   19   
1                 2  Machine Learning  157870             14760  1999   23   
2                 1  Network Security   55662              5871  1997    2   
3                 1      Data Science  134955             17284  1999   30   
4                 1  Network Security  125934             14871  1998   10   

   Weekday  Month  Age  Net Fees  Study Duration  Fee per Semester  \
0        3      1   18    135580               4         16947.500   
1        6      5   25    143110               4         17888.750   
2        1     12   27     49791               4          6223.875   
3        5     10   25    117671               4         14708.875   
4        5      1   26    111063               4         13882.875   

   Admission Age  
0             14  
1             21  
2             20  
3             22  
4             18

In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Field of Study               200000 non-null  object 
 1   Year of Admission            200000 non-null  int64  
 2   Expected Year of Graduation  200000 non-null  int64  
 3   Current Semester             200000 non-null  int64  
 4   Specialization               200000 non-null  object 
 5   Fees                         200000 non-null  int64  
 6   Discount on Fees             200000 non-null  int64  
 7   Year                         200000 non-null  int32  
 8   Day                          200000 non-null  int32  
 9   Weekday                      200000 non-null  int32  
 10  Month                        200000 non-null  int32  
 11  Age                          200000 non-null  int32  
 12  Net Fees                     200000 non-null  int64  
 13 

In [269]:
print(df['Field of Study'].nunique())  # Field of Study uchun unikal classlar soni
print(df['Specialization'].nunique())  # Specialization uchun unikal classlar soni


5
5


In [270]:
df['Field of Study'].value_counts()
df['Specialization'].value_counts()

Specialization
Web Development            40292
Machine Learning           40142
Network Security           39932
Data Science               39870
Artificial Intelligence    39764
Name: count, dtype: int64

In [271]:
df['Fee per Semester'] = df['Fee per Semester'].astype(int)

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   Field of Study               200000 non-null  object
 1   Year of Admission            200000 non-null  int64 
 2   Expected Year of Graduation  200000 non-null  int64 
 3   Current Semester             200000 non-null  int64 
 4   Specialization               200000 non-null  object
 5   Fees                         200000 non-null  int64 
 6   Discount on Fees             200000 non-null  int64 
 7   Year                         200000 non-null  int32 
 8   Day                          200000 non-null  int32 
 9   Weekday                      200000 non-null  int32 
 10  Month                        200000 non-null  int32 
 11  Age                          200000 non-null  int32 
 12  Net Fees                     200000 non-null  int64 
 13  Study Duration

In [273]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Field of Study'] = le.fit_transform(df['Field of Study'])
df['Specialization'] = le.fit_transform(df['Specialization'])


In [274]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Field of Study               200000 non-null  int64
 1   Year of Admission            200000 non-null  int64
 2   Expected Year of Graduation  200000 non-null  int64
 3   Current Semester             200000 non-null  int64
 4   Specialization               200000 non-null  int64
 5   Fees                         200000 non-null  int64
 6   Discount on Fees             200000 non-null  int64
 7   Year                         200000 non-null  int32
 8   Day                          200000 non-null  int32
 9   Weekday                      200000 non-null  int32
 10  Month                        200000 non-null  int32
 11  Age                          200000 non-null  int32
 12  Net Fees                     200000 non-null  int64
 13  Study Duration               

In [275]:
X = df.drop(columns=['Specialization'])  # Independent variables (input)

y= df['Specialization'] # Dependent variable (output)

In [276]:
from sklearn.model_selection import train_test_split

# Split the data into training and temporary testing sets (80% training, 20% testing)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)

# Split the temporary testing data into validation and testing sets (50% validation, 50% test of temp set)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)


In [277]:
clf = DecisionTreeClassifier(random_state=42)

clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [278]:
y_val_pred = clf.predict(X_val)

print("Accuracy_score on validation set: ", accuracy_score(y_val, y_val_pred))

Accuracy_score on validation set:  0.20175


In [279]:
# X_train_scaled = StandardScaler().fit_transform(X_train)
# X_val_scaled = StandardScaler().fit_transform(X_val)
# X_test_scaled = StandardScaler().fit_transform(X_test)

In [280]:
# from sklearn.model_selection import train_test_split

# Split the data into training and temporary testing sets (80% training, 20% testing)
# X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

# Split the temporary testing data into validation and testing sets (50% validation, 50% test of temp set)
# X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)


In [281]:
# clf = DecisionTreeClassifier(random_state=42)

# clf.fit(X_train_scaled, y_train)

In [282]:
#Normalization/Standardizationdagi

# y_val_pred = clf.predict(X_val_scaled)

# print("Accuracy_score on validation set: ", accuracy_score(y_val, y_val_pred))

In [283]:
# Accuracy_score on validation set:  0.20175
# Accuracy_score on validation set:  0.19916666666666666

In [284]:
# clf.fit(X_train, y_train)  # Scaling kerak emas


In [285]:
# Hyperparameter tuning (Parameterlarni o'zgartirish)

clf = DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)
clf.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)

In [286]:
# Validation uchun bashorat
y_val_pred = clf.predict(X_val)


In [287]:
from sklearn.metrics import accuracy_score

# Validation setdagi aniqlik
accuracy = accuracy_score(y_val, y_val_pred)
print("Validation accuracy: ", accuracy)


Validation accuracy:  0.2032


In [288]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [291]:
y_val_pred = clf.predict(X_val)



In [292]:
accuracy = accuracy_score(y_val, y_val_pred)
print("Validation accuracy: ", accuracy)

Validation accuracy:  0.2032


In [293]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, X_train, y_train, cv=5)
print("Cross-validation accuracy: ", scores.mean())


Cross-validation accuracy:  0.20081875


In [294]:
clf = DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)
clf.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)

Validation accuracy:  0.2032


In [297]:
from sklearn.metrics import confusion_matrix

# Confusion matrix
conf_matrix = confusion_matrix(y_val, y_val_pred)
print("Confusion Matrix:\n", conf_matrix)


Confusion Matrix:
 [[ 873    0  531    7 2566]
 [ 878    0  506    7 2545]
 [ 888    0  539    8 2598]
 [ 898    0  519    6 2648]
 [ 804    0  530    3 2646]]


In [298]:
from sklearn.metrics import classification_report

# Classification report
report = classification_report(y_val, y_val_pred)
print("Classification Report:\n", report)


Classification Report:
               precision    recall  f1-score   support

           0       0.20      0.22      0.21      3977
           1       0.00      0.00      0.00      3936
           2       0.21      0.13      0.16      4033
           3       0.19      0.00      0.00      4071
           4       0.20      0.66      0.31      3983

    accuracy                           0.20     20000
   macro avg       0.16      0.20      0.14     20000
weighted avg       0.16      0.20      0.14     20000



C:\Users\Maftuna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Maftuna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Maftuna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classi

In [299]:
# Test setdagi bashorat
y_test_pred = clf.predict(X_test)

# Test setdagi aniqlik
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test accuracy: ", test_accuracy)


Test accuracy:  0.2029
